language: cpp
sudo: false
dist: precise

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: COMPILER=g++-4.9
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=g++-5
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
      env: COMPILER=clang++-3.6
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
      env: COMPILER=clang++-3.7
    - os: osx
      compiler: clang
    - os: osx
      compiler: clang
      osx_image: xcode7.3

#before_install:
#  - sudo apt-get update -qq
#  - sudo apt-get install -y sfml

install:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="https://cmake.org/files/v3.4/cmake-3.4.3-Linux-x86_64.sh"
      CMAKE_INSTALLER="cmake-3.4.3-Linux-x86_64.sh"
      wget --no-check-certificate --quiet -O ${CMAKE_INSTALLER} - ${CMAKE_URL}
      sh ${CMAKE_INSTALLER} --prefix=$HOME --exclude-subdir
    else
      brew update
      brew unlink cmake
      brew install cmake
    fi

script:
  - |
    cd ${TRAVIS_BUILD_DIR} && pwd
    mkdir build
    cd build && pwd
    cmake -DUNIT_TEST=ON -DCMAKE_CXX_COMPILER=$COMPILER ../ && make
    src/test/geomandel_tests -s

# blacklist
branches:
  except:
    - dev
    - gh-pages

#notifications:
#  webhooks:
#    urls: https://webhooks.gitter.im/e/
#    on_success: change
#
